services:
  - type: web
    name: boston-housing-model
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: main
    region: oregon
